### PR TITLE
Paper Plugin Removal

### PR DESCRIPTION
**Pull request by WolfyScript**
Both WU and CC are compiled against 1.20.6, and Spigot 1.21 had breaking changes. Spigot has a backwards compatibility remapper, that allows 1.20.6 plugins to work on 1.21.  
Turns out Paper Plugins only support the most recent minecraft version, and disable the backwards compatibility remapper.  
**No mention about this in the [docs](https://docs.papermc.io/paper/dev/getting-started/paper-plugins)! Only that they are "experimental". Not to mention that they are basically required if you want your plugin to load properly!**

### Possible Issues
Due to the removal of the Paper Plugin (and no reintroduction in the near future), this may cause load issues on Paper servers... again!  

If you encounter any issue **enable the ["legacy" plugin loading](https://docs.papermc.io/paper/reference/paper-plugins#cyclic-plugin-loading)**
**I wont fix the loading issues caused by the new Paper loading system! I am tired of Paper!**

### CODE REVIEW

**Comment by Relaxing9** [comment]
For me Utils 4.17-beta.5 loads for my Paper server (1.21 Build 127) . with no startup errors Is it possible to just get a .6 version with the updated NBT-API nothing else (no paper plug removal)...?

**Comment by WolfyScript** [comment]
Have you tested the 4.17-beta.6 on your server? Or are there any startup issues?

Paper Plugin removal just means it no longer uses the experimental Paper feature. The plugin should still work, but **may** have issues in some configurations, that will require the ["legacy" plugin loading](https://docs.papermc.io/paper/reference/paper-plugins#cyclic-plugin-loading) to be fixed.

My rant was just about Paper making the spigot plugin loading mechanic "legacy", while using an experimental plugin loading mechanic as the default.   
The whole situation is a bit complicated and my rant may not have explained it well enough.

**Comment by Relaxing9** [comment]
> Have you tested the 4.17-beta.6 on your server? Or are there any startup issues?
> 
> Paper Plugin removal just means it no longer uses the experimental Paper feature. The plugin should still work, but **may** have issues in some configurations, that will require the ["legacy" plugin loading](https://docs.papermc.io/paper/reference/paper-plugins#cyclic-plugin-loading) to be fixed.
> 
> My rant was just about Paper making the spigot plugin loading mechanic "legacy", while using an experimental plugin loading mechanic as the default. The whole situation is a bit complicated and my rant may not have explained it well enough.

Yes, I have tested both:
- beta.5: https://mclo.gs/CETUITc
- beta.6: https://mclo.gs/SQJdzPk

However, both show NMS util version as null. I was thinking perhaps if the NBT-API depend was updated with paper support it may have a better outcome without using the "legacy" plugin loading because with my host I am unable to change startup flags.

**Comment by WolfyScript** [comment]
Oh these... they can be safely ignored.
WolfyUtils still has no 1.21 specific NMS module and relies on the Fallback. As long as there are no runtime issues, the fallback works fine. 

That's because the NMS implementation in WolfyUtils is being phased out. The latest CustomCrafting versions no longer use any NMS parts, so the fallback isn't even actually used on those versions.

The only NMS WU will keep using is from other libraries such as the NBT-Item API.

**Pull request merged**
